# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from fedscale.cloud.channels import job_api_pb2 as job__api__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in job_api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class JobServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CLIENT_REGISTER = channel.unary_unary(
                '/fedscale.JobService/CLIENT_REGISTER',
                request_serializer=job__api__pb2.RegisterRequest.SerializeToString,
                response_deserializer=job__api__pb2.ServerResponse.FromString,
                _registered_method=True)
        self.CLIENT_PING = channel.unary_unary(
                '/fedscale.JobService/CLIENT_PING',
                request_serializer=job__api__pb2.PingRequest.SerializeToString,
                response_deserializer=job__api__pb2.ServerResponse.FromString,
                _registered_method=True)
        self.CLIENT_EXECUTE_COMPLETION = channel.unary_unary(
                '/fedscale.JobService/CLIENT_EXECUTE_COMPLETION',
                request_serializer=job__api__pb2.CompleteRequest.SerializeToString,
                response_deserializer=job__api__pb2.ServerResponse.FromString,
                _registered_method=True)
        self.DOWNLOAD_DATA = channel.unary_stream(
                '/fedscale.JobService/DOWNLOAD_DATA',
                request_serializer=job__api__pb2.TransferRequest.SerializeToString,
                response_deserializer=job__api__pb2.DataChunk.FromString,
                _registered_method=True)
        self.UPLOAD_DATA = channel.stream_unary(
                '/fedscale.JobService/UPLOAD_DATA',
                request_serializer=job__api__pb2.DataChunk.SerializeToString,
                response_deserializer=job__api__pb2.UploadReply.FromString,
                _registered_method=True)


class JobServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CLIENT_REGISTER(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CLIENT_PING(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CLIENT_EXECUTE_COMPLETION(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DOWNLOAD_DATA(self, request, context):
        """Large-payload data plane.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UPLOAD_DATA(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JobServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CLIENT_REGISTER': grpc.unary_unary_rpc_method_handler(
                    servicer.CLIENT_REGISTER,
                    request_deserializer=job__api__pb2.RegisterRequest.FromString,
                    response_serializer=job__api__pb2.ServerResponse.SerializeToString,
            ),
            'CLIENT_PING': grpc.unary_unary_rpc_method_handler(
                    servicer.CLIENT_PING,
                    request_deserializer=job__api__pb2.PingRequest.FromString,
                    response_serializer=job__api__pb2.ServerResponse.SerializeToString,
            ),
            'CLIENT_EXECUTE_COMPLETION': grpc.unary_unary_rpc_method_handler(
                    servicer.CLIENT_EXECUTE_COMPLETION,
                    request_deserializer=job__api__pb2.CompleteRequest.FromString,
                    response_serializer=job__api__pb2.ServerResponse.SerializeToString,
            ),
            'DOWNLOAD_DATA': grpc.unary_stream_rpc_method_handler(
                    servicer.DOWNLOAD_DATA,
                    request_deserializer=job__api__pb2.TransferRequest.FromString,
                    response_serializer=job__api__pb2.DataChunk.SerializeToString,
            ),
            'UPLOAD_DATA': grpc.stream_unary_rpc_method_handler(
                    servicer.UPLOAD_DATA,
                    request_deserializer=job__api__pb2.DataChunk.FromString,
                    response_serializer=job__api__pb2.UploadReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fedscale.JobService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fedscale.JobService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class JobService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CLIENT_REGISTER(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fedscale.JobService/CLIENT_REGISTER',
            job__api__pb2.RegisterRequest.SerializeToString,
            job__api__pb2.ServerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CLIENT_PING(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fedscale.JobService/CLIENT_PING',
            job__api__pb2.PingRequest.SerializeToString,
            job__api__pb2.ServerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CLIENT_EXECUTE_COMPLETION(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fedscale.JobService/CLIENT_EXECUTE_COMPLETION',
            job__api__pb2.CompleteRequest.SerializeToString,
            job__api__pb2.ServerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DOWNLOAD_DATA(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/fedscale.JobService/DOWNLOAD_DATA',
            job__api__pb2.TransferRequest.SerializeToString,
            job__api__pb2.DataChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UPLOAD_DATA(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/fedscale.JobService/UPLOAD_DATA',
            job__api__pb2.DataChunk.SerializeToString,
            job__api__pb2.UploadReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
