# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: job_api.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'job_api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rjob_api.proto\x12\x08\x66\x65\x64scale\";\n\x0eServerResponse\x12\r\n\x05\x65vent\x18\x01 \x01(\t\x12\x0c\n\x04meta\x18\x02 \x01(\x0c\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"P\n\x0fRegisterRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x13\n\x0b\x65xecutor_id\x18\x02 \x01(\t\x12\x15\n\rexecutor_info\x18\x03 \x01(\x0c\"5\n\x0bPingRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x13\n\x0b\x65xecutor_id\x18\x02 \x01(\t\"\x8f\x01\n\x0f\x43ompleteRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x13\n\x0b\x65xecutor_id\x18\x02 \x01(\t\x12\r\n\x05\x65vent\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\x08\x12\x0b\n\x03msg\x18\x05 \x01(\t\x12\x13\n\x0bmeta_result\x18\x06 \x01(\t\x12\x13\n\x0b\x64\x61ta_result\x18\x07 \x01(\x0c\";\n\x0fTransferRequest\x12\x13\n\x0btransfer_id\x18\x01 \x01(\t\x12\x13\n\x0b\x65xecutor_id\x18\x02 \x01(\t\"\xa5\x01\n\tDataChunk\x12\x13\n\x0btransfer_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63hunk_index\x18\x02 \x01(\x03\x12\x14\n\x0ctotal_chunks\x18\x03 \x01(\x03\x12\x13\n\x0btotal_bytes\x18\x04 \x01(\x03\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\x0c\x12\x11\n\tclient_id\x18\x06 \x01(\t\x12\x13\n\x0b\x65xecutor_id\x18\x07 \x01(\t\x12\r\n\x05\x65vent\x18\x08 \x01(\t\"p\n\x0bUploadReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0btransfer_id\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12*\n\x08response\x18\x04 \x01(\x0b\x32\x18.fedscale.ServerResponse2\xf0\x02\n\nJobService\x12H\n\x0f\x43LIENT_REGISTER\x12\x19.fedscale.RegisterRequest\x1a\x18.fedscale.ServerResponse\"\x00\x12@\n\x0b\x43LIENT_PING\x12\x15.fedscale.PingRequest\x1a\x18.fedscale.ServerResponse\"\x00\x12R\n\x19\x43LIENT_EXECUTE_COMPLETION\x12\x19.fedscale.CompleteRequest\x1a\x18.fedscale.ServerResponse\"\x00\x12\x43\n\rDOWNLOAD_DATA\x12\x19.fedscale.TransferRequest\x1a\x13.fedscale.DataChunk\"\x00\x30\x01\x12=\n\x0bUPLOAD_DATA\x12\x13.fedscale.DataChunk\x1a\x15.fedscale.UploadReply\"\x00(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'job_api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SERVERRESPONSE']._serialized_start=27
  _globals['_SERVERRESPONSE']._serialized_end=86
  _globals['_REGISTERREQUEST']._serialized_start=88
  _globals['_REGISTERREQUEST']._serialized_end=168
  _globals['_PINGREQUEST']._serialized_start=170
  _globals['_PINGREQUEST']._serialized_end=223
  _globals['_COMPLETEREQUEST']._serialized_start=226
  _globals['_COMPLETEREQUEST']._serialized_end=369
  _globals['_TRANSFERREQUEST']._serialized_start=371
  _globals['_TRANSFERREQUEST']._serialized_end=430
  _globals['_DATACHUNK']._serialized_start=433
  _globals['_DATACHUNK']._serialized_end=598
  _globals['_UPLOADREPLY']._serialized_start=600
  _globals['_UPLOADREPLY']._serialized_end=712
  _globals['_JOBSERVICE']._serialized_start=715
  _globals['_JOBSERVICE']._serialized_end=1083
# @@protoc_insertion_point(module_scope)
